spring:
  application:
    name: Temp-Store


  security:
    oauth2:
      resource-server:
        jwt:
          #Uno dei seguenti url serve per verificare l'autenticità del token ricevuto
          jwk-set-uri: http://localhost:8180/realms/realm_prog/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/realm_prog


#Configurazione dell'unità di persistenza
  datasource:
    url: jdbc:postgresql://localhost:5432/database_psw
    password: Computer@2002
    driver-class-name: org.postgresql.Driver
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect #usato per convertire le query da JPQL in quelle specifiche di postgres
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  ssl:
    key-store-password: computer
    key-store-type: PKCS12
    enabled: true
    key-store: C:\Users\aless\Desktop\Progetto_PSW\src\main\resources\keytool\localhost-ssl.p12
  port: 9190

  compression:
    enabled: 'true'





